### ISSUE TITLE
Generovat API dokumentaci apigenem.

### ISSUE THREAD

**Issue by PetrP** [PetrP/Orm#18]
http://orm.petrprochazka.com/api/
http://orm.petrprochazka.com/api/v0.2.1/

plus jí dávat do archivu na stažení

**Comment by JanTvrdik** [comment]
Chybí mi fakt hodně, prosím o zvýšení priority :)

**Comment by PetrP** [comment]
+1

**Comment by honzasladek** [comment]
+4 O:-)

**Comment by PetrP** [comment]
Mám to ready. Jen musim jestě udělat nejaké úpravy. Protože to negeneruje dobre.

**Comment by PetrP** [comment]
Done.

Zatim je vygenerovana jen dev verze 0.3.0.

http://orm.petrprochazka.com/api/v0.3.0-dev/
- [php53](http://orm.petrprochazka.com/api/v0.3.0-dev/php53)
- [php52](http://orm.petrprochazka.com/api/v0.3.0-dev/php52)
