### ISSUE TITLE
manytomany->remove($entity) se nepromítne do mapperu

### ISSUE THREAD

**Issue by ViliamKopecky** [PetrP/Orm#2]
Koukal jsem do kódu, a ohledně tohohle tam jsou věci dost zakomentovaný, tak předpokládám, že je známo. 

Např:

$article->tags->remove($tag);

v kódu který by následoval to funguje dobře. Ale myslim, že se změny nepromítnou do mapperu nebo databáze (prostě v databází se záznam ve spojovací tabulce nesmaže).

**Comment by PetrP** [comment]
A co přesně nefunguje? Máš vyskoušené že to nefunguje nebo si to myslíš na základě zakomentovaných řádků? :-)

"Koukal jsem do kódu ... myslim, že se změny nepromítnou do mapperu." :-)

Jinak jeden řádek je zakomentovaný [tady](https://github.com/Clevisaci/Orm/blob/v0.2/Orm/Relationships/ManyToMany.php#L81) a to je jen poznamka v kodu pro me.
Nemá vliv na funkčnost.

A druhý zakomentovaný řádek je [tady](https://github.com/Clevisaci/Orm/blob/v0.2/Orm/Relationships/ManyToMany.php#L171) což je pozůstatek z doby kdy se entity při odpojení (za uřcitého stavu) mazali.

Ani jedno nijak nesouvisí s mazáním a předáváním do mapperu.

V remove se přidá do [property del](https://github.com/Clevisaci/Orm/blob/v0.2/Orm/Relationships/ManyToMany.php#L102). V persist se přeřadí do proměné [$del](https://github.com/Clevisaci/Orm/blob/v0.2/Orm/Relationships/ManyToMany.php#L172) a pak se [předá do mapperu](https://github.com/Clevisaci/Orm/blob/v0.2/Orm/Relationships/ManyToMany.php#L188) a tam například DibiManyToManyMapper [vykonává sql DELETE](https://github.com/Clevisaci/Orm/blob/v0.2/Orm/Relationships/DibiManyToManyMapper.php#L87).

**Comment by ViliamKopecky** [comment]
Zkoušel jsem na tomhle kódu (Je to uvnitř presenteru, unittest by byl asi hezčí, ale to až po školení ;) ).

``` php
$articles = $this->model->getRepository('Articles');
$a = $articles->getById(1);

dd($a->tags->count()); 
    // 3 správně

dd((int) \dibi::query('SELECT COUNT(*) FROM [articletags] WHERE [article_id] = %i', $a->id)->fetchSingle());
    // 3 správně

foreach($a->tags as $tag) {
    $a->tags->remove($tag);
}

dd($a->tags->count());
    // 0 správně

dd((int) \dibi::query('SELECT COUNT(*) FROM [articletags] WHERE [article_id] = %i', $a->id)->fetchSingle());
    // 3 správně (ještě nepersistováno)

$articles->persistAndFlush($a);

dd($a->tags->count());
    // 0 správně

dd((int) \dibi::query('SELECT COUNT(*) FROM [articletags] WHERE [article_id] = %i', $a->id)->fetchSingle());
    // 3 špatně (teď už by to měla být změna vidět v databázi)

```

Ani dibi profiler se neukazuje žádný pokus o SQL DELETE.

**Comment by PetrP** [comment]
Je to jiny bug, o kterym vim. Entita se v tomle pripade neoznaci jako
zmenena. Muzes to udelat rucne.

```
$e->markAsChanged('tags');
```

**Comment by ViliamKopecky** [comment]
Dík, takhle už to funguje.
