### ISSUE TITLE
Api nemá statické metody.

### ISSUE THREAD

**Issue by PetrP** [PetrP/Orm#27]
http://orm.petrprochazka.com/forum/post/312/#p312

**Comment by cabadaj** [comment]
Mozna to bude tim, ze u nekterych sunkci je `@internal`. Az ted jsem si toho vsimnul. APIGen je pak ignoruje, ale lze zapnout, aby je akceptoval nejakym prepinacem.

**Comment by PetrP** [comment]
Hmmm jenom `@internal` to nebude protože např [Repository::hydrateEntity()](http://orm.petrprochazka.com/api/v0.3.0/php53/class-Orm.Repository.html#_hydrateEntity) je taky internal, ale zobrazuje se.

Nevíš o nějaké další metodě která se nezobrazuje?

---

Btw proč je `MetaData::getEntityRules()` internal? :-)
