### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by Vrtak-CZ** [PetrP/Orm#47]
add composer

**Comment by PetrP** [comment]
Nemám s composerem skušenosti. Ale rozhodně je to dobrý nápad.

Jen nevím jak vyřešit to že stažitelnou verzi generuju pro php53 / 52. Šlo by místo dávat je na github mít je někde na internetu třeba jako tar balíčky?

**Comment by Vrtak-CZ** [comment]
Composer není pro PHP 5.2 použitelný. Požaduje min 5.3.2, doporučená je 5.3.4 a novější.

**Comment by Vrtak-CZ** [comment]
Jinak co se týká balíčků
1) možnost je že se "balíčky" generují automaticky z tagů a větví které obsahují composer.json (github je generuje) composer na ně pouze odkazuje.
2) možnost je v composer.json specifikovat verzi a URL pro stažení balíčku

**Comment by JanTvrdik** [comment]
Variantu (2) považuji za lepší a vadí mi, že to tak Nette nedělá.

**Comment by paranoiq** [comment]
jak načíst Orm Composerem do projektu (jde samozřejmě o dočasné řešení):
1) nemá composer.json a bereme ze zipu - definujeme vlastní package
2) jsou tam dvě verze a nejde vzít podadresář - tak scriptem mažeme verzi pro php52

```
    "repositories": [{
        "type": "package",
        "package": {
            "name": "PetrP/Orm",
            "version": "v0.4",
            "dist": {
                "type": "zip",
                "url": "http://orm.petrprochazka.com/download/Orm-v0.4.0-RC6.zip"
            }
        }
    }],
    "require": {
        "php": ">= 5.3.0",
        "nette/nette": "@dev",
        "dg/dibi": "dev-master",
        "PetrP/Orm": "v0.4"
    },
    "scripts":
    {
        "post-install-cmd": "rm -rf ./libs/PetrP/Orm/php52",
        "post-update-cmd": "rm -rf ./libs/PetrP/Orm/php52"
    }
```

**Comment by PetrP** [comment]
Může mi někdo vysvětlit jakou má tohle výhodu? Při aktualizaci stejně musíš aktualizovat url.

**Comment by paranoiq** [comment]
za stávajícího stavu musím v každém případě, pokud chci aktualizovat

výhodou je: jedno místo, kde jsou uvedeny závislosti, dokumentace odkud se ta knihovna vzala, ulehčení při aktualizaci (nemusím to stahovat a rozbalovat)

btw. problém s generováním stažitelné verze by šel vyřešit i tak, že by se to composerem stáhlo nezbuildované a po instalaci se spustila post-install-cmd událost, která by spustila to generování

**Comment by JanTvrdik** [comment]
Nebo by šel vytvořit [custom installer](http://getcomposer.org/doc/articles/custom-installers.md).

**Comment by PetrP** [comment]
#64
