### ISSUE TITLE
Zabránit v entitě definici vazebních properties stejných jako klíčové property entit (např. $order)

### ISSUE THREAD

**Issue by paranoiq** [PetrP/Orm#56]
tohle: https://github.com/PetrP/Orm/blob/v0.4/Orm/Relationships/OneToMany.php#L265 způsobí selhání při persistování nebo poškozená data, pokud je definována vazba 1:m přes property jménem $order. asi by chtělo ve fázi parsování anotací upozornit na to, že daná property je klíčové slovo. jinak je to hrozné WTF

**Comment by PetrP** [comment]
Díky za report.

Order v OneToMany je historickej pozůstatek. Pokusím se to v budoucí verzi odstranit (a přidám způsob jak si něco takového implementovat).

Problém je že aby ho OnaToMany pohla použít musí existovat, takže by nešla vyhazovat chybu když ho defunguješ.
Další problém je že momentální implementace ani nefunguje (když je nepřidáš najednou ale v postupně tak bude vždy 0).

**Comment by JanTvrdik** [comment]
Teď jsme na to narazili u Tripilotu. Nepěkná vlastnost.

**Comment by PetrP** [comment]
Už to mám opravené pokusím se to tento víkend dostat ven.

**Comment by PetrP** [comment]
Lze to teď vypnout:

``` php
/**
 * @property My\OneToMany $articles {1:m ArticlesRepository $author}
 */
class User extends Orm\Entity
{

}
```

``` php
class My\OneToMany extends Orm\OneToMany
{
    protected function getOrderProperty()
    {
        return NULL;
    }
}
```

V budoucí verzi bude to že se automaticky použije `order` když je k dispozici odstraněno a tuhle funkci bude potřeba explicitně zapnout.
