### ISSUE TITLE
Entity: nekonzistence chování __set(), setValue() a setValues()

### ISSUE THREAD

**Issue by paranoiq** [PetrP/Orm#57]
`__set()` napřed hledá metodu setXyz() a až pak nastavuje property
`setValues()` zkusí nastavit property a až pak zkusí najít metodu setXyz()
`setValue()` pouze nastavuje property

je to velmi matoucí a není jasné, co je vlastně správný postup

pokud chci nastavit několik properties najednou pomocí setValues() a jedna z nich má setter, tak se nespustí

**Comment by PetrP** [comment]
Něco zřejmě používáš špatně.

Mějmě entitu:

``` php
/**
 * @property mixed $foo
 */
class Foo extends Orm\Entity
{

}
```

'Magické' property na entitě, které jsou definované v anotaci nemají skutečnou property na třídě. Když by měli, vedlo by to k naprosto neočekávanému chování (v závislosti na viditelnosti). (Pravděpodobně by to mělo vyhazovat chybu.)

Property lze nastavit (obdobně i číst) třema naprosto rovnejma způsobama:

Jako property:
(doporučeno z venku entity)

``` php
$foo->foo = 'abc';
```

Setter metodou (která nemusí existovat):
(doporučeno zevnitř entity)

``` php
$foo->setFoo('abc');
```

Jako pole:
(nedoporučeno :-))

``` php
$foo['foo'] = 'abc';
```

<hr>

V případě že potřebuješ můžeš si přetížit vlastní setter (obdobně i getter)

``` php
public function setFoo($foo)
{
    return parent::setFoo($foo);
}
```

`parent::setFoo` ve skutečnosti neexistuje, je to jen syntax který umožňuje jednoduší použití. Ve skutečnosti se vola (protected metoda) `setValue` která je určena pro volání uvnitř setteru např. v případě ze magické parent settery nelze použít http://orm.petrprochazka.com/forum/topic/96/entity-magicke-pretezovani-settru-a-gettru/

Setter se volá (automaticky) při všech třech výše zmíněných možnostech toho jak nastavit hodnotu.

<hr>

setValues je jen pomocná metoda (kterou bych nejraději odstranil).

Která defakto dělá toto:

``` php
foreach ($values as $property => $value) $entity->{$property} = $value;
```

S tím rozdílem že ignoruje neexistující property.

Může to defakto znamenat že se buď nastaví 'maxická' property nastavená v anotaci, nebo public property (která může existovat i když se nebude používat pro persistenci, protože není obsažena v metadatech entity) nebo public setter, který se může existovat nezávisle na 'magickych' property (viz príklad):

``` php
/**
 * @property $firstName
 * @property $lastName
 */
class User extends Orm\Entity
{
    public function setName($name)
    {
        // toto je pouze ilustracni priklad
        list($this->firstName, $this->lastName) = explode(' ', $name, 2);
    }
}

$users->setValues(array('name' => 'Pepa Novák'));
```

Používání setValues bych extra nedoporučoval. Existuje jen velmy malé množství usecasů kde se hodí, a obrovské množství kde se nehodí.

**Comment by PetrP** [comment]
Jinak abych odpověděl na nadpis: `nekonzistence chování __set(), setValue() a setValues()` 

Tak konzistence tam není potřeba, metody spolu nemají moc společného.

> `__set()` napřed hledá metodu setXyz() a až pak nastavuje property

`__set` je magická php metoda umožnující reakci na nastavování neexistujících property.
Není určena aby jí uzivatel nijak volal.
V entitě když to hodně zjednoduším, tak dělá toto: `__get($k, $v) { return $this->{'set' . $k}($v); }`

> `setValue()` pouze nastavuje property

Je protected metoda, která se může volat uvnitř přetíženého setteru v případě že nelze použít magické parent metody. A nastavuje magické property definované v anotaci. `$this->setValue('foo', $value)` je to samé jako `parent::setFoo($value)` a stejně jako parent metodu nedává (většinou) smysl volat jí jinde než v přetížené metodě.

> je to velmi matoucí a není jasné, co je vlastně správný postup

Správný postup k čemu?

> pokud chci nastavit několik properties najednou pomocí setValues() a jedna z nich má setter, tak se nespustí

Spustí.
`$e->setValues(array('foo' => $value))` je to samé jako `$e->foo = $value`. A tedy se očekávej to samé chování. (V připadě že existuje public property tak se nastaví; jinak se zavolá `__set`, která zavolá `setFoo`)

**Comment by PetrP** [comment]
Podobné příspěvky patří spíš na fórum do [sekce dokumentace](http://orm.petrprochazka.com/forum/forum/4/dokumentace/). Protože to není problém který by šel fixnout úpravou nějakého kódu, ale spíš problém absence dokumentace.

Nebo i v jiných kategoriích fóra (když si nejsi jistý jestli to neni bug).

Výhoda fóra je:
- Texy, v kterém dokážu psát odpověd mnohem pohodlněji než na gihubu. 
- Z fóra mi chodí notifikace které neignoruju. Z githubu mi chodí desítky emailů denně které nečtu.
- Po vyřešení na fóru může někomu dalšímu posloužit jako řešení jeho problému. Na githubu po zavření defakto zmizí.
- Při změnách funkčnosti vyhledávám na fóru relevantní témata a přidávám informace, jak se případné řešení změnilo.

**Comment by paranoiq** [comment]
ad fórum: věci, kterými si nejsem jistý tam píšu. nad touhle jsem dlouho váhal a ověřoval to, než jsem to dal sem. a teď vidím, že jsem to ověřil špatně.

k dokumentaci něco postnu na fórum...
