### ISSUE TITLE
kolekce by měly deklarovat rozhraní Countable

### ISSUE THREAD

**Issue by paranoiq** [PetrP/Orm#60]

**Comment by PetrP** [comment]
Oni jsou Countable https://github.com/PetrP/Orm/blob/v0.4/Orm/Mappers/Collection/IEntityCollection.php#L19

Nebo tím myslíš něco jiného?

**Comment by paranoiq** [comment]
omlouvám se. omyl. bug v PHPStormu - neumí napovídat poděděný interface. měl jsem si to ověřit, ale člověk těm nástroječkům tak nějak věří...
