### ISSUE TITLE
zpětná lomítka v zip archivu v buildu

### ISSUE THREAD

**Issue by paranoiq** [PetrP/Orm#61]
@PetrP můžeš prosím fixnout Zipper::add(), aby překládal backslash na normální lomítko a zbuildovat znovu poslední verzi? soubory se zpětným lomítkem nejdou správně rozbalit na Macu a na Linuxu

**Comment by PetrP** [comment]
Asi to samé jako tady http://orm.petrprochazka.com/forum/topic/162/zip-archivy-maji-na-linuxu-fileroller-spatnou-strukturu/

Je tam archiv, kde jsem zkusil opravu, ale potřebuju od někoho (komu to nefunguje) potvrdit že to funguje.

**Comment by tsusanka** [comment]
@PetrP @paranoiq funguje - viz forum.

**Comment by tsusanka** [comment]
@PetrP ping

**Comment by PetrP** [comment]
? http://orm.petrprochazka.com/forum/post/645/#p645

**Comment by tsusanka** [comment]
aj díky, nevšmil jsem si nové verze
